# Generated by Django 3.2.12 on 2023-04-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='seccion',
            field=models.CharField(max_length=50, verbose_name='Sección del producto'),
        ),
    ]
